# App\Entity\Product;
#   properties:
#     name:
#       - NotBlank: { message: "Le nom du produit est obligatoire" }
#       - Length: { min: 3, max: 255, minMessage: "Le nom du produit doit faire plus de 3 caractères." }
#     price:
#       - NotBlank: { message: "Le prix du produit est obligatoire." }
#     category:
#       - NotBlank: { message: "Le choix de la catégorie est obligatoire" }
#     shortDescription:
#       - NotBlank: {message: "La description est obligatoire" }
#       - Length: {min: 10, minMessage: "La description doit faire plus de 10 caractères." }
